site_name: Py Resounding Libraries
site_author: Nicholas Cornia
repo_url: https://github.com/NicholasCorniaOrpheus/py-resounding-libraries
nav:
  - Home: index.md
  - Installation: installation.md
  - Modules: modules.md 
  - Tutorials: tutorials.md
  - Koha Reports: reports.md
  - API Documentation: api_documentation.md

plugins:
  - search
  - mkdocstrings

extra_css:
  - assets/css/extras.css


theme:
  name: material
  language: en
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      abstract: fontawesome/solid/book
      note: fontawesome/solid/note-sticky
      quote: fontawesome/solid/quote-left

  font:
      text: Crimson Pro
  palette:
    - scheme: default
      primary: custom
      default: custom
      footer: custom
      accent: custom       

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - search.share
    - toc.integrate
    #- navigation.footer
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.top
    #- toc.follow
    #- toc

copyright: Copyright &copy; 2026 Orpheus Instituut, Resounding Libraries

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NicholasCorniaOrpheus/py-resounding-libraries
      name: GitHub repository
  social:
    - icon: material/music-note
      link: https://orpheusinstituut.be/
      name: Orpheus Instituut

markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # icons extension!
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
