from omeka_s_tools.api import OmekaAPIClient
import requests
from pyreslib import koha
import os
import json, csv


### TO-DO
"""
1. Filter records with digitization and create new items and associated media in Omeka S via API.
2. Update record information via biblio_id and auth_id fields between Koha and Omeka S.
"""


def omekas_session(api_url: str, key_identity: str, key_credential: str):
    """
    Args:
        api_url (str): API URL for your Omeka S instance.
        key_identity (str): Omeka S key identity for the user.
        key_credential (str): Omeka S key credential for the user.

    Returns:
        omekas_session: `omeka_s_tools` session
    """
    omekas_session = OmekaAPIClient(
        api_url=omekas_credentials["api_url"],
        key_identity=omekas_credentials["key_identity"],
        key_credential=omekas_credentials["key_credential"],
    )
    return omekas_session


def csv2dict(csv_filename):  # imports a CSV file as dictionary
    f = open(csv_filename, "r")
    reader = csv.DictReader(f)
    d = {"items": []}
    for row in reader:
        d["items"].append(row)
    return d["items"]


def generate_omekas_mapping(mappings_directory: str) -> dict:
    """
    Generates a dictionary from a series of CSV files (auth,biblio,media...).
    Args:
        mappings_directory (str): Path of csv mapping files.
    Returns:
        A dictionary of mappings.
    """
    omekas_mapping = {}

    # get authorities mapping
    omekas_mapping["auth"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - auth.csv")
    )
    # biblio mapping
    omekas_mapping["biblio"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - biblio.csv")
    )
    # get media mapping
    omekas_mapping["media"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - media.csv")
    )
    # get locations
    omekas_mapping["locations"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - locations.csv")
    )
    # get research groups
    omekas_mapping["research_groups"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - research_groups.csv")
    )

    # get researchers
    omekas_mapping["researchers"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - researchers.csv")
    )

    # get projects
    omekas_mapping["projects"] = csv2dict(
        os.path.join(mappings_directory, "koha-omekas_mapping - projects.csv")
    )

    return omekas_mapping


def change_item_property_value(
    session: OmekaAPIClient,
    value: str,
    property_name: str,
    resource_id: int,
    resource_type: str,
    value_position: int = 0,
):
    """Change the value of a specific statement of a property of a given resource.
    Args:
        session: `omeka_s_tools` session generated by [pyreslib.omekas.omekas_session].
        value (str): new value for the property.
        property_name (str): name of the property to be updated, such as `dcterms:title`.
        resource_id (int): ID of the item set to be added to the site.
        resource_type (str): Resource type, such as `items`, `item_sets` and `media`.
        value_position (int): position of the value to be change, in case of multiple statements for property. 0 is default.

    Returns:
        `None`

    """
    data = session.get_resource_by_id(resource_id, resource_type=resource_type)
    data[property_name][value_position]["@value"] = value
    session.update_resource(data, resource_type=resource_type)
